### ISSUE TITLE
Error in make on Mac OS 

### ISSUE THREAD

**Issue by chaz9456** [searchivarius/nmslib#105]
in /similarity_search/include/method/hnsw.h
: error: use of undeclared identifier '_MM_HINT_T0' _mm_prefetch((char _)(_iter)->getData(), _MM_HINT_T0);

-did notice issue for testing Mac OS on new version. 
-issues also arise with "__m128" and others in /similarity_search/src/method/hnsw_distfunc_opt.cc when bypassing the previous errors with a workaround

**Comment by searchivarius** [comment]
Hi, thank you for reporting. Yes, the current version may not build on Mac. Our next goal is to make it fully Mac compatible. HNSW also won't work properly if you build using Clang. We are working on fixing this.

BTW, which compiler do you use?

**Comment by chaz9456** [comment]
i was using clang. thank you.

**Comment by searchivarius** [comment]
@chaz9456 could you try the develop branch? if clang doesn't work could you try gcc?
BTW, if you don't want to build fancy stuff, there are no dependencies on 3rd party libraries.
Thank you!

**Comment by searchivarius** [comment]
It looks like the build should work now thanks to @bileg fixes. I am closing the issue.

**Comment by chaz9456** [comment]
Thanks! can't wait to give it a try.

**Comment by searchivarius** [comment]
Actually @bileg used Clang, but if it works with GCC, it would be a nice confirmation.

**Comment by ianseyer** [comment]
I still get this error on both `master` and `dev` running macOS Sierra. Have manually installed `gcc` via HomeBrew and run cmake with `-DCMAKE_C_COMPILER=`/usr/bin/gcc` to no avail.

**Comment by searchivarius** [comment]
@ianseyer which branch?
Thanks!

**Comment by searchivarius** [comment]
Hi @ianseyer thanks to @bileg this should now work in master. If it doesn't feel free to re-open the ticket and bug us.
